
name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:



permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run:  nohup python app.py & 
      
    - name: Run curl command
      run: curl http://localhost:5000